name: ptyrad
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - accelerate
  - h5py
  - jupyter
  - matplotlib
  - optuna
  - python=3.12
  - pytorch=3.5.1
  - pytorch-cuda
  - scikit-learn
  - scipy
  - tifffile
  - torchvision

  - numba
